version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: my_mysql
    volumes:
      - /docker/mysql/mydir:/mydir
      - /docker/mysql/datadir:/var/lib/mysql
      - /docker/mysql/conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - /docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=mm6wAjpad4hKgu"
      - "MYSQL_DATABASE=stock4j"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
